package at.angular.gradle

import org.gradle.api.DefaultTask
import org.gradle.api.Project
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import org.jetbrains.kotlin.gradle.targets.js.webpack.KotlinWebpack

/**
 * Emit the one webpack tweak every JIT AngularKt app needs, identically: prepend `zone.js` and
 * `@angular/compiler` to the webpack entry so they evaluate before any `@angular` ES module.
 */
internal fun Project.configureJitWebpackConfig() {
    val fragmentFile = layout.projectDirectory.file("webpack.config.d/angularkt-jit.generated.js")
    val generate = tasks.register("angularKtGenerateJitWebpackConfig", GenerateJitWebpackConfigTask::class.java) {
        group = "angularkt"
        description = "Generate the framework-mandatory JIT webpack.config.d fragment (zone.js + @angular/compiler entry prepend)."
        fragment.set(fragmentFile)
    }
    // The fragment lands inside the config dir KGP reads, so every webpack task (build + dev-server
    // run, all of type KotlinWebpack) must wait for it to exist before assembling the config.
    tasks.withType(KotlinWebpack::class.java).configureEach { dependsOn(generate) }
}

/**
 * Writes the static JIT webpack fragment. The body mirrors what consumers previously wrote by hand;
 * the leading guard is what makes it a no-op in AOT mode (the Kotlin/JS target is a `library()`
 * there, which has no executable webpack entry — so `config.entry.main` is absent).
 */
abstract class GenerateJitWebpackConfigTask : DefaultTask() {
    @get:OutputFile
    abstract val fragment: RegularFileProperty

    @TaskAction
    fun generate() {
        fragment.get().asFile.writeText(FRAGMENT)
    }

    private companion object {
        val FRAGMENT = """
            |// GENERATED by the AngularKt Gradle plugin — DO NOT EDIT (regenerated every build).
            |// zone.js and @angular/compiler must run before any @angular module is evaluated.
            |// Angular libraries ship in "partial" Ivy format: their `ɵfac = ɵɵngDeclareFactory(...)`
            |// initializers JIT-link at class-definition time and throw if @angular/compiler isn't
            |// loaded yet; zone.js must patch the environment first too.
            |if (config.entry && Array.isArray(config.entry.main)) {
            |    config.entry.main = ['zone.js', '@angular/compiler', ...config.entry.main];
            |}
        """.trimMargin() + "\n"
    }
}
