import app.BootstrapModule
import app.startAppKoin
import at.angular.generated.registerAngularKt
import at.angular.platformBrowserDynamic.platformBrowserDynamic

/**
 * JIT entry — classic `platformBrowserDynamic().bootstrapModule(...)`, the textbook Angular JIT path
 * (the dynamic platform bundles `@angular/compiler`, which compiles [BootstrapModule]'s templates at
 * runtime). `registerAngularKt()` (generated by the KSP processor from this module's annotations)
 * applies the `@Component`/`@NgModule` decorators first — the JIT counterpart to AOT's compiled bridges.
 */
fun main() {
    // Bring up the Koin container before Angular renders (see the "Koin DI" example).
    startAppKoin()
    registerAngularKt()
    platformBrowserDynamic(undefined)
        .bootstrapModule(BootstrapModule::class.js)
        .catch { e -> console.error("Bootstrap failed:", e) }
}
