@file:OptIn(ExperimentalJsExport::class)

import app.BootstrapModule
import app.appProviders
import app.startAppKoin
import at.angular.core.EnvironmentProviders
import at.angular.generated.registerAngularKt
import at.angular.platformBrowser.bootstrapApplication
import at.angular.utils.jsObject

/**
 * Both bootstrap entries live here in the shared source set; the active build picks one.
 *
 * The JIT build is an executable, so Kotlin/JS auto-runs [main]. The AOT build is a library whose
 * generated `main.ts` imports and calls the exported [mainAot]. Kotlin/JS would normally auto-run a
 * zero-arg `main()` on module load even for a library, which would fire the JIT [main] when the AOT
 * `main.ts` imports the module — so the plugin compiles the AOT target with `-main noCall`, leaving
 * [main] as dead code there (tree-shaken out, along with its dynamic `platform-browser-dynamic`
 * import). The two entries need distinct names because `@JsExport` can't export two `main` overloads.
 */

/**
 * JIT entry — classic `platformBrowserDynamic().bootstrapModule(...)`, the textbook Angular JIT path
 * (the dynamic platform bundles `@angular/compiler`, which compiles [BootstrapModule]'s templates at
 * runtime). `registerAngularKt()` (generated by the KSP processor from this module's annotations)
 * applies the `@Component`/`@NgModule` decorators first — the JIT counterpart to AOT's compiled bridges.
 * In the AOT library build this function is never called, and `registerAngularKt()` is a generated no-op.
 *
 * `@angular/platform-browser-dynamic` is loaded with a dynamic `import()` on purpose, not the static
 * `at.angular.platformBrowserDynamic` external. A static reference would emit a top-level
 * `import '@angular/platform-browser-dynamic'` in the compiled module, which — since this file is shared
 * with the AOT build — would drag that package (and `@angular/compiler`) into the AOT module graph and
 * add ~0.5 MB to the AOT bundle. As a dynamic import inside this dead-in-AOT function, esbuild tree-shakes
 * it away entirely, so the AOT bundle stays compiler-free (the whole point of AOT).
 */
fun main() {
    // Bring up the Koin container before Angular renders (see the "Koin DI" example).
    startAppKoin()
    registerAngularKt()
    val platformBrowserDynamicModule: dynamic = js("import('@angular/platform-browser-dynamic')")
    platformBrowserDynamicModule.then { module: dynamic ->
        module.platformBrowserDynamic(undefined)
            .bootstrapModule(BootstrapModule::class.js)
            .catch { e: dynamic -> console.error("Bootstrap failed:", e) }
    }
}

/**
 * AOT entry — standalone `bootstrapApplication`, the modern Angular idiom and today's `ng new`
 * default. The processor-generated `main.ts` is a thin shim: it imports the AOT-compiled
 * [app.RootComponent] bridge and the root `@RoutingModule`'s providers (`importProvidersFrom`), then hands
 * both to this `mainAot`. Templates are already compiled, so `@angular/compiler` stays out of the bundle.
 * In the JIT executable build this function is dead code.
 */
@JsExport
fun mainAot(root: JsClass<*>, providers: Array<EnvironmentProviders>) {
    // Bring up the Koin container before Angular renders (see the "Koin DI" example).
    startAppKoin()
    bootstrapApplication(
        rootComponent = root,
        options = jsObject {
            this.providers = appProviders() + providers
        }
    ).catch { e -> console.error("Bootstrap failed:", e) }
}
